// backend/src/controllers/reportExportController.ts
import { Request, Response } from 'express';
import { getDB, getAsync, allAsync } from '../models/db';
import ExcelJS from 'exceljs';

// ============================================
// GET /api/reports/export/excel
// ============================================
export const exportReportToExcel = async (req: Request, res: Response) => {
  try {
    const { fiscal_year } = req.query;
    const db = getDB();
    const targetFiscalYear = fiscal_year || '2025-26';

    // Fetch all active indicators
    const indicators = await allAsync<any[]>(db, 
      `SELECT id, code, name, category, weight, max_score as maxScore 
       FROM indicators 
       WHERE is_active = 1 
       ORDER BY display_order, category`,
      []
    );

    // Get category groupings
    const categories = Array.from(new Set(indicators.map(ind => ind.category)));

    // Fetch system thresholds from system_config
    let highThreshold = 80;
    let mediumThreshold = 50;
    
    try {
      const highConfig = await getAsync<any>(
        db,
        `SELECT config_value FROM system_config WHERE config_key = 'integrity.threshold.high'`,
        []
      );
      if (highConfig && highConfig.config_value) {
        highThreshold = Number(highConfig.config_value);
      }
      
      const mediumConfig = await getAsync<any>(
        db,
        `SELECT config_value FROM system_config WHERE config_key = 'integrity.threshold.medium'`,
        []
      );
      if (mediumConfig && mediumConfig.config_value) {
        mediumThreshold = Number(mediumConfig.config_value);
      }
    } catch (error) {
      console.warn('Could not fetch thresholds from system_config, using defaults:', error);
    }

    // Fetch agency data with dynamic indicators
    const agencies = await allAsync<any[]>(db, 
      `SELECT 
        a.id, 
        a.name AS agency, 
        a.sector,
        a.contact_email, 
        a.contact_phone,
        a.status,
        SUM(id.score) as total_score,
        SUM(i.weight) as max_score
      FROM agencies a
      LEFT JOIN indicator_data id ON a.id = id.agency_id 
        AND id.fiscal_year = ?
        AND id.status = 'final'
      LEFT JOIN indicators i ON id.indicator_id = i.id AND i.is_active = 1
      WHERE a.status = 'active'
      GROUP BY a.id, a.name, a.sector, a.contact_email, a.contact_phone, a.status
      ORDER BY total_score DESC`,
      [targetFiscalYear]
    );

    // Fetch individual indicator scores for each agency
    const indicatorScores = await allAsync<any[]>(db,
      `SELECT 
        a.id as agency_id,
        a.name as agency_name,
        i.id as indicator_id,
        i.code as indicator_code,
        id.score
      FROM agencies a
      CROSS JOIN indicators i
      LEFT JOIN indicator_data id ON a.id = id.agency_id 
        AND id.indicator_id = i.id
        AND id.fiscal_year = ?
        AND id.status = 'final'
      WHERE a.status = 'active'
        AND i.is_active = 1
      ORDER BY a.name, i.display_order`,
      [targetFiscalYear]
    );

    // Create a map of agency scores
    const scoreMap = new Map();
    indicatorScores.forEach(score => {
      const key = `${score.agency_id}_${score.indicator_id}`;
      scoreMap.set(key, score.score || 0);
    });

    // Create workbook
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AIMS System';
    workbook.lastModifiedBy = 'System Admin';
    workbook.created = new Date();
    workbook.modified = new Date();

    // Sheet 1: Summary
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Report Information', key: 'label', width: 30 },
      { header: 'Value', key: 'value', width: 30 }
    ];
    
    const summaryData = [
      { label: 'Fiscal Year', value: targetFiscalYear },
      { label: 'Total Agencies', value: agencies.length },
      { label: 'Total Indicators', value: indicators.length },
      { label: 'Categories', value: categories.join(', ') },
      { label: 'High Integrity Threshold', value: `${highThreshold}%` },
      { label: 'Medium Integrity Threshold', value: `${mediumThreshold}%` },
      { label: 'Generated On', value: new Date().toLocaleString() },
      { label: 'Generated By', value: 'AIMS System' }
    ];

    summaryData.forEach(row => summarySheet.addRow(row));

    // Style summary sheet header
    summarySheet.getRow(1).eachCell(cell => {
      cell.font = { bold: true };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFE0E7FF' }
      };
    });

    // Sheet 2: Indicators Configuration
    const configSheet = workbook.addWorksheet('Indicators');
    configSheet.columns = [
      { header: 'Code', key: 'code', width: 15 },
      { header: 'Indicator Name', key: 'name', width: 40 },
      { header: 'Category', key: 'category', width: 20 },
      { header: 'Weight', key: 'weight', width: 10 },
      { header: 'Max Score', key: 'maxScore', width: 10 }
    ];

    indicators.forEach(ind => {
      configSheet.addRow({
        code: ind.code || '',
        name: ind.name,
        category: ind.category,
        weight: `${ind.weight || 0}%`,
        maxScore: ind.maxScore || 100
      });
    });

    // Style config sheet header
    configSheet.getRow(1).eachCell(cell => {
      cell.font = { bold: true };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFE0E7FF' }
      };
    });

    // Sheet 3: Agency Scores (main sheet)
    const scoresSheet = workbook.addWorksheet('Agency Scores');
    
    // Build dynamic columns
    const scoreColumns: any[] = [
      { header: 'Agency', key: 'agency', width: 25 },
      { header: 'Sector', key: 'sector', width: 15 },
      { header: 'Status', key: 'status', width: 12 }
    ];

    // Add category subtotals columns
    categories.forEach(category => {
      scoreColumns.push({
        header: `${category.replace('_', ' ')} Score`,
        key: `${category}_score`,
        width: 18
      });
      scoreColumns.push({
        header: `${category.replace('_', ' ')} %`,
        key: `${category}_percent`,
        width: 15
      });
    });

    // Add overall scores
    scoreColumns.push(
      { header: 'Total Score', key: 'total_score', width: 12 },
      { header: 'Max Score', key: 'max_score', width: 12 },
      { header: 'Percentage', key: 'percentage', width: 12 },
      { header: 'Integrity Level', key: 'level', width: 20 },
      { header: 'Contact Email', key: 'email', width: 25 },
      { header: 'Contact Phone', key: 'phone', width: 15 }
    );

    scoresSheet.columns = scoreColumns;

    // Group indicators by category
    const indicatorsByCategory: Record<string, any[]> = {};
    indicators.forEach(ind => {
      if (!indicatorsByCategory[ind.category]) {
        indicatorsByCategory[ind.category] = [];
      }
      indicatorsByCategory[ind.category].push(ind);
    });

    // Process each agency
    agencies.forEach(agencyRow => {
      const agencyData: any = {
        agency: agencyRow.agency,
        sector: agencyRow.sector,
        status: agencyRow.status === 'active' ? 'Active' : agencyRow.status,
        email: agencyRow.contact_email || '',
        phone: agencyRow.contact_phone || ''
      };

      // Calculate category scores
      const categoryTotals: Record<string, { score: number; max: number }> = {};
      
      for (const [category, inds] of Object.entries(indicatorsByCategory)) {
        categoryTotals[category] = { score: 0, max: 0 };
        
        for (const indicator of inds) {
          const score = scoreMap.get(`${agencyRow.id}_${indicator.id}`) || 0;
          categoryTotals[category].score += score;
          categoryTotals[category].max += indicator.maxScore || 100;
        }
      }

      // Add category data to row
      categories.forEach(category => {
        const catData = categoryTotals[category] || { score: 0, max: 0 };
        agencyData[`${category}_score`] = catData.score.toFixed(1);
        agencyData[`${category}_percent`] = catData.max > 0 
          ? `${((catData.score / catData.max) * 100).toFixed(1)}%` 
          : '0%';
      });

      // Overall scores
      const totalScore = parseFloat(agencyRow.total_score) || 0;
      const maxScore = parseFloat(agencyRow.max_score) || indicators.reduce((sum, ind) => sum + (ind.maxScore || 100), 0);
      const percentage = maxScore > 0 ? (totalScore / maxScore) * 100 : 0;
      
      agencyData.total_score = totalScore.toFixed(1);
      agencyData.max_score = maxScore.toFixed(1);
      agencyData.percentage = `${percentage.toFixed(1)}%`;

      // Determine integrity level
      if (percentage >= highThreshold) {
        agencyData.level = 'Strong Integrity Culture';
      } else if (percentage >= mediumThreshold) {
        agencyData.level = 'Moderate Integrity Culture';
      } else {
        agencyData.level = 'Needs Improvement';
      }

      scoresSheet.addRow(agencyData);
    });

    // Style scores sheet header
    scoresSheet.getRow(1).eachCell(cell => {
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF4F46E5' }
      };
    });

    // Sheet 4: Detailed Indicator Scores (if manageable number of indicators)
    if (indicators.length <= 20) {
      const detailSheet = workbook.addWorksheet('Detailed Scores');
      const detailColumns: any[] = [
        { header: 'Agency', key: 'agency', width: 25 },
        { header: 'Sector', key: 'sector', width: 15 }
      ];

      indicators.forEach(ind => {
        detailColumns.push({
          header: ind.code || ind.name.substring(0, 20),
          key: `ind_${ind.id}`,
          width: 12
        });
      });

      detailColumns.push(
        { header: 'Total', key: 'total', width: 12 },
        { header: 'Percentage', key: 'percent', width: 12 }
      );

      detailSheet.columns = detailColumns;

      agencies.forEach(agencyRow => {
        const detailRow: any = {
          agency: agencyRow.agency,
          sector: agencyRow.sector
        };

        let total = 0;
        indicators.forEach(ind => {
          const score = scoreMap.get(`${agencyRow.id}_${ind.id}`) || 0;
          detailRow[`ind_${ind.id}`] = score.toFixed(1);
          total += score;
        });

        const totalMaxScore = indicators.reduce((sum, ind) => sum + (ind.maxScore || 100), 0);
        detailRow.total = total.toFixed(1);
        detailRow.percent = totalMaxScore > 0 ? `${((total / totalMaxScore) * 100).toFixed(1)}%` : '0%';
        
        detailSheet.addRow(detailRow);
      });

      // Style detail sheet header
      detailSheet.getRow(1).eachCell(cell => {
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FF4F46E5' }
        };
      });
    }

    // Generate buffer and send directly
    const buffer = await workbook.xlsx.writeBuffer();
    
    // Set response headers
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="AIMS_Report_${targetFiscalYear}.xlsx"`);
    
    // Send buffer - buffer is a Buffer object, we can send it directly
    // Express automatically handles Buffer objects
    res.send(buffer);
    
  } catch (err) {
    console.error('Excel export error:', err);
    res.status(500).json({ 
      error: 'Failed to generate Excel report',
      details: err instanceof Error ? err.message : 'Unknown error'
    });
  }
};