// backend/src/controllers/reportExportController.ts
import { Request, Response } from 'express';
import { getDB } from '../models/db';
import ExcelJS from 'exceljs';
import { createWriteStream } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';

export const exportReportToExcel = async (req: Request, res: Response) => {
  try {
    const { fiscal_year } = req.query;
    const db = getDB();
  try {
    const targetFiscalYear = fiscal_year || '2025-26';

    // Fetch all active indicators
    const indicators = await new Promise<any[]>((resolve, reject) => {
      await allAsync(db, 
        `SELECT id, code, name, category, weight, maxScore 
         FROM indicators 
         WHERE is_active = 1 
         ORDER BY display_order, category`,
        (err, rows) => (err ? reject(err) : resolve(rows || []))
      );
    });

    // Get category groupings
    const categories = Array.from(new Set(indicators.map(ind => ind.category)));

    // Fetch system thresholds
    const thresholds = await new Promise<any>((resolve, reject) => {
      await getAsync(db, 
        `SELECT 
          MAX(CASE WHEN config_key = 'high_integrity_min' THEN config_value END) as high,
          MAX(CASE WHEN config_key = 'medium_integrity_min' THEN config_value END) as medium
         FROM system_config`,
        (err, row) => (err ? reject(err) : resolve(row || {}))
      );
    });

    // Fetch agency data with dynamic indicators
    const agenciesQuery = `
      SELECT 
        a.id, a.name AS agency, a.sector,
        a.contact_email, a.contact_phone,
        GROUP_CONCAT(DISTINCT i.id || ':' || COALESCE(id.score, 0)) as indicator_scores,
        SUM(id.score) as total_score,
        SUM(i.weight) as max_score
      FROM agencies a
      LEFT JOIN indicator_data id ON a.id = id.agency_id 
        AND id.fiscal_year = ?
        AND id.status = 'final'
      LEFT JOIN indicators i ON id.indicator_id = i.id AND i.is_active = 1
      WHERE a.status = 'active'
      GROUP BY a.id, a.name, a.sector, a.contact_email, a.contact_phone
      ORDER BY total_score DESC`;

    const agencies = await new Promise<any[]>((resolve, reject) => {
      await allAsync(db, agenciesQuery, [targetFiscalYear], (err, rows) => {
        if (err) return reject(err);
        resolve(rows || []);
      });
    });

    // Create workbook
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AIMS System';
    workbook.lastModifiedBy = 'System Admin';
    workbook.created = new Date();
    workbook.modified = new Date();

    // Sheet 1: Summary
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Report Information', key: 'label', width: 30 },
      { header: 'Value', key: 'value', width: 30 }
    ];
    
    const summaryData = [
      { label: 'Fiscal Year', value: targetFiscalYear },
      { label: 'Total Agencies', value: agencies.length },
      { label: 'Total Indicators', value: indicators.length },
      { label: 'Categories', value: categories.join(', ') },
      { label: 'High Integrity Threshold', value: `${thresholds.high || 80}%` },
      { label: 'Medium Integrity Threshold', value: `${thresholds.medium || 50}%` },
      { label: 'Generated On', value: new Date().toLocaleString() },
      { label: 'Generated By', value: 'AIMS System' }
    ];

    summaryData.forEach(row => summarySheet.addRow(row));

    // Sheet 2: Indicators Configuration
    const configSheet = workbook.addWorksheet('Indicators');
    configSheet.columns = [
      { header: 'Code', key: 'code', width: 15 },
      { header: 'Indicator Name', key: 'name', width: 40 },
      { header: 'Category', key: 'category', width: 20 },
      { header: 'Weight', key: 'weight', width: 10 },
      { header: 'Max Score', key: 'maxScore', width: 10 }
    ];

    indicators.forEach(ind => {
      configSheet.addRow({
        code: ind.code || '',
        name: ind.name,
        category: ind.category,
        weight: `${ind.weight}%`,
        maxScore: ind.maxScore
      });
    });

    // Sheet 3: Agency Scores (main sheet)
    const scoresSheet = workbook.addWorksheet('Agency Scores');
    
    // Build dynamic columns
    const scoreColumns: any[] = [
      { header: 'Agency', key: 'agency', width: 25 },
      { header: 'Sector', key: 'sector', width: 15 }
    ];

    // Add category subtotals columns
    categories.forEach(category => {
      scoreColumns.push({
        header: `${category.replace('_', ' ')} Score`,
        key: `${category}_score`,
        width: 15
      });
      scoreColumns.push({
        header: `${category.replace('_', ' ')} %`,
        key: `${category}_percent`,
        width: 12
      });
    });

    // Add overall scores
    scoreColumns.push(
      { header: 'Total Score', key: 'total_score', width: 12 },
      { header: 'Max Score', key: 'max_score', width: 12 },
      { header: 'Percentage', key: 'percentage', width: 12 },
      { header: 'Integrity Level', key: 'level', width: 20 },
      { header: 'Contact Email', key: 'email', width: 25 },
      { header: 'Contact Phone', key: 'phone', width: 15 }
    );

    scoresSheet.columns = scoreColumns;

    // Process each agency
    agencies.forEach(agencyRow => {
      const agencyData: any = {
        agency: agencyRow.agency,
        sector: agencyRow.sector,
        email: agencyRow.contact_email || '',
        phone: agencyRow.contact_phone || ''
      };

      // Parse indicator scores
      const scoreMap = new Map();
      if (agencyRow.indicator_scores) {
        agencyRow.indicator_scores.split(',').forEach((pair: string) => {
          const [indId, score] = pair.split(':');
          scoreMap.set(indId, parseFloat(score));
        });
      }

      // Calculate category scores
      const categoryTotals: Record<string, { score: number; max: number }> = {};
      
      indicators.forEach(indicator => {
        const score = scoreMap.get(indicator.id) || 0;
        const max = indicator.maxScore || 0;
        
        if (!categoryTotals[indicator.category]) {
          categoryTotals[indicator.category] = { score: 0, max: 0 };
        }
        categoryTotals[indicator.category].score += score;
        categoryTotals[indicator.category].max += max;
      });

      // Add category data to row
      categories.forEach(category => {
        const catData = categoryTotals[category] || { score: 0, max: 0 };
        agencyData[`${category}_score`] = catData.score.toFixed(1);
        agencyData[`${category}_percent`] = catData.max > 0 
          ? `${((catData.score / catData.max) * 100).toFixed(1)}%` 
          : 'N/A';
      });

      // Overall scores
      const totalScore = parseFloat(agencyRow.total_score) || 0;
      const maxScore = parseFloat(agencyRow.max_score) || indicators.reduce((sum, ind) => sum + (ind.maxScore || 0), 0);
      const percentage = maxScore > 0 ? (totalScore / maxScore) * 100 : 0;
      
      agencyData.total_score = totalScore.toFixed(1);
      agencyData.max_score = maxScore.toFixed(1);
      agencyData.percentage = `${percentage.toFixed(1)}%`;

      // Determine integrity level
      const highThreshold = thresholds.high ? Number(thresholds.high) : 80;
      const mediumThreshold = thresholds.medium ? Number(thresholds.medium) : 50;
      
      if (percentage >= highThreshold) {
        agencyData.level = 'Strong Integrity Culture';
      } else if (percentage >= mediumThreshold) {
        agencyData.level = 'Moderate Integrity Culture';
      } else {
        agencyData.level = 'Needs Improvement';
      }

      scoresSheet.addRow(agencyData);
    });

    // Sheet 4: Detailed Indicator Scores (if needed)
    if (indicators.length <= 20) { // Only create if manageable number of indicators
      const detailSheet = workbook.addWorksheet('Detailed Scores');
      const detailColumns: any[] = [
        { header: 'Agency', key: 'agency', width: 25 },
        { header: 'Sector', key: 'sector', width: 15 }
      ];

      indicators.forEach(ind => {
        detailColumns.push({
          header: ind.code || ind.name.substring(0, 20),
          key: `ind_${ind.id}`,
          width: 12
        });
      });

      detailColumns.push(
        { header: 'Total', key: 'total', width: 12 },
        { header: 'Percentage', key: 'percent', width: 12 }
      );

      detailSheet.columns = detailColumns;

      agencies.forEach(agencyRow => {
        const detailRow: any = {
          agency: agencyRow.agency,
          sector: agencyRow.sector
        };

        // Parse indicator scores
        const scoreMap = new Map();
        if (agencyRow.indicator_scores) {
          agencyRow.indicator_scores.split(',').forEach((pair: string) => {
            const [indId, score] = pair.split(':');
            scoreMap.set(indId, parseFloat(score));
          });
        }

        let total = 0;
        indicators.forEach(ind => {
          const score = scoreMap.get(ind.id) || 0;
          detailRow[`ind_${ind.id}`] = score.toFixed(1);
          total += score;
        });

        detailRow.total = total.toFixed(1);
        detailRow.percent = `${(total / indicators.reduce((sum, i) => sum + (i.maxScore || 0), 0) * 100).toFixed(1)}%`;
        
        detailSheet.addRow(detailRow);
      });
    }

    // Apply styling
    [summarySheet, configSheet, scoresSheet].forEach((sheet, index) => {
      if (sheet.columns) {
        sheet.getRow(1).eachCell(cell => {
          cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F46E5' } };
        });
      }
    });

    // Generate temp file
    const tempPath = join(tmpdir(), `AIMS_Report_${targetFiscalYear}_${Date.now()}.xlsx`);
    await workbook.xlsx.writeFile(tempPath);

    // Send file
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="AIMS_Report_${targetFiscalYear}.xlsx"`);
    
    const stream = createWriteStream(tempPath);
    stream.pipe(res);
    
  } catch (err: any) {
    console.error('Excel export error:', err);
    res.status(500).json({ error: 'Failed to generate Excel report' });
  }
};